### ISSUE TITLE
Snyk: videx-wellog - August 2024

### ISSUE THREAD

**Issue by GuillaumeVix** [equinor/videx-wellog#264]
## Description
Recurring task to fix videx-wellog vulnerabilities.

Have a look at the equinor/videx-wellog [vulnearibilities](https://app.snyk.io/org/videx/projects?groupBy=targets&before&after&searchQuery=&sortBy=highest+severity&filters[Show]=&filters[Integrations]=&filters[CollectionIds]=)

- [examples/storybook/package.json](https://app.snyk.io/org/videx/project/7c300ae6-937b-4821-9cd6-6ffa320dc2d0)
- [package.json](https://app.snyk.io/org/videx/project/74506eb6-512a-419e-8297-9f66428e0a4d)
- [Code Analysis](https://app.snyk.io/org/videx/project/2d7032b8-f8d0-4fba-bf40-1b495ddb4e79)

![Image](https://github.com/user-attachments/assets/ead54400-c391-4842-831f-fd0c19ab2559)

## How to test
Repository equinor/videx-wellog [vulnearibilities](https://app.snyk.io/org/videx/projects?groupBy=targets&before&after&searchQuery=&sortBy=highest+severity&filters[Show]=&filters[Integrations]=&filters[CollectionIds]=) should not have vulnerabilities equal or above 'Medium'.

## Acceptance criteria
1. Videx-wellog repository does not have any detected vulnerability equal or above 'Medium' (only 'low' are discarded)

**Comment by VRiveland** [comment]
### Replaced some packages
#### jsdom => jest-environment-jsdom
This is the preferred way of setting up tests using jsdom, according to the jest docks
#### rollup-plugin-terser =>@rollup/plugin-terser
The former is deprecated.

### Some packages can't be updated yet
#### Eslint, same as in REP main repo, have to wait until the plugins support v9
Eslint-config-airbnb-base are working on it https://github.com/airbnb/javascript/issues/2961
Eslint-config-airbnb-typescript are working on it, but have to wait for the base before they can complete their tasks https://github.com/iamturns/eslint-config-airbnb-typescript/issues/331
Eslint-formatter-table - not working on it, hasn't been published in 3 years. I suggest we remove this dependency.
eslint-plugin-import - might be working on it https://github.com/import-js/eslint-plugin-import/issues/2948
#### Jest
v30 is in alpha stages, so the version we're using is still considered latest. Hopefully they update soon. The issues caused by jest are only medium severity though, so not too much of an issue yet.
#### copyfiles
Only medium severity issue, but the package also hasn't been updated in 4 years. Should any more serius issues appear we might want to consider replacing it.
